import {parseCatalogDecimal,validCatalogId,type Product} from "@/lib/product-catalog";
export const PAYMENT_METHODS={pix:"Pix",cash:"Dinheiro",card:"Cartão"} as const;export type PaymentMethod=keyof typeof PAYMENT_METHODS;export type SaleStatus="draft"|"completed";
export type SaleItemInput={product_id:string;quantity:string;unit_price:string};export type SaleInput={customer_name:string;payment_method:string;items:SaleItemInput[]};
export type Sale={id:string;status:SaleStatus;customer_name:string|null;payment_method:PaymentMethod|null;total_amount:string|number;completed_at:string|null;created_at:string;item_count?:number};
export type SaleItem={id:string;product_id:string;quantity:string|number;unit_price:string|number;product:{name:string;unit:string;active:boolean}|null};
function text(value:unknown){if(typeof value!=="string")throw new Error("Revise o cliente.");const result=value.trim();if(result.length>160)throw new Error("Cliente: informe até 160 caracteres.");return result;}
export function parseSaleInput(input:unknown):SaleInput{if(!input||typeof input!=="object")throw new Error("Revise os dados da venda.");const data=input as Record<string,unknown>;if(typeof data.payment_method!=="string"||(data.payment_method!==""&&!Object.hasOwn(PAYMENT_METHODS,data.payment_method)))throw new Error("Selecione um pagamento válido.");if(!Array.isArray(data.items)||data.items.length<1||data.items.length>200)throw new Error("Adicione ao menos um produto.");const seen=new Set<string>();const items=data.items.map(raw=>{if(!raw||typeof raw!=="object")throw new Error("Revise os itens da venda.");const item=raw as Record<string,unknown>;if(!validCatalogId(item.product_id)||seen.has(item.product_id))throw new Error("Não repita o mesmo produto na venda.");seen.add(item.product_id);const quantity=parseCatalogDecimal(item.quantity,3)!,unit_price=parseCatalogDecimal(item.unit_price,2)!;if(Number(quantity)<=0)throw new Error("A quantidade deve ser maior que zero.");return {product_id:item.product_id,quantity,unit_price};});return {customer_name:text(data.customer_name),payment_method:data.payment_method,items};}
export function saleError(error:{code?:string;message?:string}){const message=error.message??"";if(message.includes("positive_total_required"))return "O total da venda deve ser maior que zero para finalizar.";if(message.includes("payment_required"))return "Selecione a forma de pagamento antes de finalizar.";if(message.includes("already_completed")||message.includes("completed_read_only"))return "Esta venda já foi finalizada e não pode ser alterada.";if(message.includes("cross_tenant")||message.includes("product_unavailable")||error.code==="23503")return "Um produto não está disponível para este negócio.";if(error.code==="23505")return "Não repita o mesmo produto na venda.";if(error.code==="42501")return "Você não tem acesso a esta operação.";return "Não foi possível salvar a venda. Revise os dados e tente novamente.";}
export function saleSubtotal(quantity:string|number,price:string|number){return Number(quantity)*Number(price)}
export function emptySale(products:Product[]):SaleInput{const first=products.find(p=>p.active);return {customer_name:"",payment_method:"",items:first?[{product_id:first.id,quantity:"1",unit_price:String(first.sale_price).replace(".",",")}]:[]};}
