begin;
create extension if not exists pgtap with schema extensions;
create temp table invite_results(result text);
create temp table invite_ids(key text primary key,id uuid);
grant select,insert on invite_results,invite_ids to authenticated,anon;
insert into invite_results select no_plan();
insert into auth.users(id,email) values
 ('ae700000-0000-4000-8000-000000000001','platform70@example.test'),
 ('ae700000-0000-4000-8000-000000000002','client70@example.test'),
 ('ae700000-0000-4000-8000-000000000003','other70@example.test'),
 ('ae700000-0000-4000-8000-000000000004','existing70@example.test'),
 ('ae700000-0000-4000-8000-000000000005','rollback70@example.test');
insert into private.platform_admins(user_id) values('ae700000-0000-4000-8000-000000000001');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"ae700000-0000-4000-8000-000000000002","role":"authenticated"}',true);
insert into invite_results select throws_ok($$select public.create_platform_provisioned_business('Forbidden','forbidden-70',null)$$,'42501','platform_forbidden','ordinary user cannot provision');
select set_config('request.jwt.claims','{"sub":"ae700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into invite_ids select 'a',public.create_platform_provisioned_business('Prepared A','prepared-70-a','11999999999');
insert into invite_results select throws_ok($$select public.accept_business_invite(repeat('a',64))$$,'42501','invite_platform_admin','platform admin cannot assume ownership through invitation');
insert into invite_ids select 'b',public.create_platform_provisioned_business('Prepared B','prepared-70-b',null);
insert into invite_ids select 'rollback',public.create_platform_provisioned_business('Rollback','prepared-70-rollback',null);
insert into invite_results select is((public.get_platform_business_access((select id from invite_ids where key='a'))->>'status'),'preparation','preparation derived');
insert into invite_results select lives_ok($$select public.authorize_platform_business_configuration((select id from invite_ids where key='a'))$$,'explicit configuration context');
reset role;
insert into invite_results select is((select count(*) from public.business_members where business_id in(select id from invite_ids)),0::bigint,'businesses have no owner');
insert into invite_results select is((select count(*) from public.business_members where user_id='ae700000-0000-4000-8000-000000000001'),0::bigint,'platform never becomes member');
insert into invite_results select is((select count(*) from public.business_settings where business_id in(select id from invite_ids)),3::bigint,'settings initialized');
insert into invite_results select is((select count(*) from public.booking_groups where business_id in(select id from invite_ids)),6::bigint,'two groups per business');
insert into invite_results select is((select count(*) from public.business_modules where business_id=(select id from invite_ids where key='a') and enabled and module='scheduling'),1::bigint,'scheduling default preserved');
insert into invite_results select is((select count(*) from public.business_modules where business_id=(select id from invite_ids where key='a') and enabled and module<>'scheduling'),0::bigint,'other modules default off');
insert into invite_results select is((select configuration_access_by from private.assisted_businesses where business_id=(select id from invite_ids where key='a')),'ae700000-0000-4000-8000-000000000001'::uuid,'configuration actor recorded');
update public.business_modules set enabled=true where business_id=(select id from invite_ids where key='a') and module='management';
create temp table before_config as select to_jsonb(s) data from public.business_settings s where business_id=(select id from invite_ids where key='a');
create temp table before_modules as select jsonb_agg(to_jsonb(m) order by module) data from public.business_modules m where business_id=(select id from invite_ids where key='a');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"ae700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into invite_results select lives_ok($$select public.generate_platform_business_invite((select id from invite_ids where key='a'),repeat('a',64))$$,'generate invite');
insert into invite_results select is(public.get_platform_business_access((select id from invite_ids where key='a'))->>'status','waiting','waiting derived');
insert into invite_results select ok(not (public.get_platform_business_access((select id from invite_ids where key='a'))::text like '%token_hash%'),'platform read does not recover secret');
reset role;
insert into invite_results select is((select token_hash from public.business_invites where business_id=(select id from invite_ids where key='a')),repeat('a',64),'only supplied hash persisted');
insert into invite_results select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name='business_invites' and column_name in('token','raw_token','link')),'no raw token/link column');
insert into invite_results select is((select expires_at-created_at from public.business_invites where token_hash=repeat('a',64)),interval '7 days','default expiry seven days');
insert into invite_results select is((select created_by from public.business_invites where token_hash=repeat('a',64)),'ae700000-0000-4000-8000-000000000001'::uuid,'creator recorded');
set local role anon;
select set_config('request.jwt.claims','{"role":"anon"}',true);
insert into invite_results select is(public.get_business_invite_public(repeat('a',64)),jsonb_build_object('status','pending','businessName','Prepared A'),'public inspection minimal');
insert into invite_results select is(public.get_business_invite_public('invalid'),'{"status":"invalid"}'::jsonb,'invalid reveals nothing');
insert into invite_results select throws_ok($$select * from public.business_invites$$,'42501',null,'anon cannot read table');
insert into invite_results select throws_ok($$select public.accept_business_invite(repeat('a',64))$$,'42501',null,'anon cannot accept');
insert into invite_results select ok(public.get_public_booking_page('prepared-70-a') is not null,'public page works without owner');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"ae700000-0000-4000-8000-000000000002","role":"authenticated"}',true);
insert into invite_results select throws_ok($$select public.generate_platform_business_invite((select id from invite_ids where key='a'),repeat('b',64))$$,'42501','platform_forbidden','ordinary user cannot generate');
insert into invite_results select throws_ok($$select public.revoke_platform_business_invite((select id from invite_ids where key='a'))$$,'42501','platform_forbidden','ordinary user cannot revoke');
insert into invite_results select throws_ok($$select public.authorize_platform_business_configuration((select id from invite_ids where key='b'))$$,'42501','platform_forbidden','manipulated configuration business blocked');
insert into invite_results select throws_ok($$select * from public.business_invites$$,'42501',null,'authenticated no generic select');
select set_config('request.jwt.claims','{"sub":"ae700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select public.generate_platform_business_invite((select id from invite_ids where key='a'),repeat('b',64));
insert into invite_results select is(public.get_business_invite_public(repeat('a',64)),'{"status":"revoked"}'::jsonb,'regeneration revokes old');
select public.revoke_platform_business_invite((select id from invite_ids where key='a'));
insert into invite_results select is(public.get_business_invite_public(repeat('b',64)),'{"status":"revoked"}'::jsonb,'explicit revoke works');
select public.generate_platform_business_invite((select id from invite_ids where key='a'),repeat('c',64));
reset role;
update public.business_invites set created_at=now()-interval '8 days',expires_at=now()-interval '1 day' where token_hash=repeat('c',64);
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"ae700000-0000-4000-8000-000000000002","role":"authenticated"}',true);
insert into invite_results select is(public.get_business_invite_public(repeat('c',64)),'{"status":"expired"}'::jsonb,'expired inspection');
insert into invite_results select throws_ok($$select public.accept_business_invite(repeat('c',64))$$,'22023','invite_expired','expiry rechecked at acceptance');
insert into invite_results select throws_ok($$select public.accept_business_invite(repeat('b',64))$$,'22023','invite_unavailable','revoked rejected');
select set_config('request.jwt.claims','{"sub":"ae700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select public.generate_platform_business_invite((select id from invite_ids where key='a'),repeat('d',64));
select public.generate_platform_business_invite((select id from invite_ids where key='b'),repeat('e',64));
select public.generate_platform_business_invite((select id from invite_ids where key='rollback'),repeat('f',64));
select set_config('request.jwt.claims','{"sub":"ae700000-0000-4000-8000-000000000002","role":"authenticated"}',true);
insert into invite_results select is(public.accept_business_invite(repeat('d',64)),'{"businessName":"Prepared A"}'::jsonb,'accept provisioned business');
insert into invite_results select throws_ok($$select public.accept_business_invite(repeat('d',64))$$,'22023','invite_unavailable','double accept rejected');
insert into invite_results select throws_ok($$select public.accept_business_invite(repeat('e',64))$$,'23505','invite_member_exists','existing membership cannot acquire B');
insert into invite_results select throws_ok($$select public.create_business_with_owner('Duplicate','duplicate-70',null)$$,'23505','user already has a business','onboarding primitive cannot create second business after invite');
insert into invite_results select is((select count(*) from public.businesses where id=(select id from invite_ids where key='b')),0::bigint,'owner A cannot read B');
insert into invite_results select throws_ok($$select * from public.business_invites$$,'42501',null,'owner still cannot read invite table');
select set_config('request.jwt.claims','{"sub":"ae700000-0000-4000-8000-000000000003","role":"authenticated"}',true);
insert into invite_results select throws_ok($$select public.accept_business_invite(repeat('d',64))$$,'22023','invite_unavailable','second user cannot reuse link');
reset role;
insert into invite_results select is((select count(*) from public.business_members where business_id=(select id from invite_ids where key='a') and role='owner'),1::bigint,'one owner only');
insert into invite_results select is((select accepted_by from public.business_invites where token_hash=repeat('d',64)),'ae700000-0000-4000-8000-000000000002'::uuid,'accepted actor');
insert into invite_results select ok((select accepted_at is not null and status='accepted' from public.business_invites where token_hash=repeat('d',64)),'accepted timestamp and state');
insert into invite_results select is((select to_jsonb(s) from public.business_settings s where business_id=(select id from invite_ids where key='a')),(select data from before_config),'configuration untouched');
insert into invite_results select is((select jsonb_agg(to_jsonb(m) order by module) from public.business_modules m where business_id=(select id from invite_ids where key='a')),(select data from before_modules),'module configuration untouched');
insert into invite_results select is((select count(*) from public.businesses where slug like 'prepared-70-%'),3::bigint,'accept did not create business');
-- Force failure after membership insertion: both writes must roll back.
create function pg_temp.fail_invite_accept() returns trigger language plpgsql as $$ begin if new.token_hash=repeat('f',64) and new.status='accepted' then raise exception 'test_rollback'; end if; return new; end $$;
create trigger test_invite_failure before update on public.business_invites for each row execute function pg_temp.fail_invite_accept();
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"ae700000-0000-4000-8000-000000000005","role":"authenticated"}',true);
insert into invite_results select throws_ok($$select public.accept_business_invite(repeat('f',64))$$,'P0001','test_rollback','acceptance failure is atomic');
reset role;
insert into invite_results select is((select count(*) from public.business_members where user_id='ae700000-0000-4000-8000-000000000005'),0::bigint,'failed acceptance leaves no owner');
insert into invite_results select is((select status from public.business_invites where token_hash=repeat('f',64)),'pending','failed acceptance leaves pending');
insert into public.business_members(business_id,user_id,role) values((select id from invite_ids where key='b'),'ae700000-0000-4000-8000-000000000004','owner');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"ae700000-0000-4000-8000-000000000003","role":"authenticated"}',true);
insert into invite_results select throws_ok($$select public.accept_business_invite(repeat('e',64))$$,'22023','invite_unavailable','business acquired during auth cannot be taken');
select set_config('request.jwt.claims','{"sub":"ae700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into invite_results select throws_ok($$select public.generate_platform_business_invite((select id from invite_ids where key='a'),repeat('0',64))$$,'23505','invite_owner_exists','no invite for owned business');
insert into invite_results select is(public.get_platform_business_access((select id from invite_ids where key='a'))->>'status','active','active derived from owner');
insert into invite_results select ok(public.get_platform_business_access((select id from invite_ids where key='a'))->'owner'->>'email'='client70@example.test','platform sees owner email');
insert into invite_results select * from finish();
select result from invite_results;
rollback;
