"use client";
import Link from "next/link";
import { useMemo,useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { Plus,Trash2 } from "lucide-react";
import { confirmPurchaseDraft,savePurchaseDraft } from "@/app/admin/compras/actions";
import { PageHeader } from "@/components/ui/page-header";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input,Label,Select } from "@/components/ui/field";
import { emptyPurchase,parsePurchaseInput,purchaseSubtotal,type Purchase,type PurchaseInput,type PurchaseItem } from "@/lib/purchases";
import { formatCatalogBRL,type Product } from "@/lib/product-catalog";

export function PurchaseEditor({purchase,items,products}:{purchase:Purchase|null;items:PurchaseItem[];products:Product[]}){
 const router=useRouter();const readonly=purchase?.status==="confirmed";const initial:PurchaseInput=purchase?{supplier_name:purchase.supplier_name??"",purchase_date:purchase.purchase_date,notes:purchase.notes??"",items:items.map(i=>({product_id:i.product_id,quantity:String(i.quantity).replace(".",","),unit_cost:String(i.unit_cost).replace(".",",")}))}:emptyPurchase(products);
 const [form,setForm]=useState(initial);const [error,setError]=useState("");const [pending,startTransition]=useTransition();const total=useMemo(()=>form.items.reduce((sum,item)=>sum+purchaseSubtotal(item.quantity.replace(",","."),item.unit_cost.replace(",",".")),0),[form.items]);
 const productMap=new Map(products.map(product=>[product.id,product]));
 function field<K extends keyof PurchaseInput>(key:K,value:PurchaseInput[K]){setForm(current=>({...current,[key]:value}));}
 function itemField(index:number,key:keyof PurchaseInput["items"][number],value:string){setForm(current=>({...current,items:current.items.map((item,i)=>i===index?{...item,[key]:value}:item)}));}
 function submit(confirm:boolean){setError("");try{parsePurchaseInput(form)}catch(validation){setError((validation as Error).message);return}startTransition(async()=>{try{const result=confirm?await confirmPurchaseDraft(purchase?.id??null,form):await savePurchaseDraft(purchase?.id??null,form);if(!result.ok||!result.data){setError(result.message);return}router.push(`/admin/compras/${result.data.id}`);router.refresh();}catch{setError("Não foi possível salvar agora. Tente novamente.")}});}
 if(readonly)return <><PageHeader title="Detalhe da compra" description="Esta compra já foi adicionada ao estoque." action={<Badge variant="success">Confirmada</Badge>}/><Card padding="md" className="mt-6 space-y-5"><dl className="grid gap-4 sm:grid-cols-3"><div><dt className="text-xs text-muted">Data</dt><dd className="font-medium">{new Intl.DateTimeFormat("pt-BR").format(new Date(`${purchase.purchase_date}T12:00:00`))}</dd></div><div><dt className="text-xs text-muted">Fornecedor</dt><dd className="font-medium">{purchase.supplier_name||"Não informado"}</dd></div><div><dt className="text-xs text-muted">Total</dt><dd className="font-semibold">{formatCatalogBRL(purchase.total_amount)}</dd></div></dl>{purchase.notes&&<div><p className="text-xs text-muted">Observações</p><p className="text-sm">{purchase.notes}</p></div>}<ul className="divide-y border-y">{items.map(item=><li key={item.id} className="grid gap-1 py-3 sm:grid-cols-[minmax(0,1fr)_7rem_8rem_8rem]"><span className="font-medium">{item.product?.name??"Produto indisponível"}{item.product&&!item.product.active?" (inativo)":""}</span><span>{item.quantity} {item.product?.unit}</span><span>{formatCatalogBRL(item.unit_cost)}</span><span className="font-semibold">{formatCatalogBRL(purchaseSubtotal(item.quantity,item.unit_cost))}</span></li>)}</ul><div className="flex justify-end"><Link href="/admin/compras" className="focus-ring rounded-xl border px-4 py-2.5 text-sm font-semibold hover:bg-surface">Voltar para compras</Link></div></Card></>;
 return <><PageHeader title={purchase?"Editar compra":"Nova compra"} description="Salve como rascunho ou confirme para adicionar os itens ao estoque."/><Card padding="md" className="mt-6"><form className="space-y-6" onSubmit={event=>{event.preventDefault();submit(false)}}><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="purchase-supplier">Fornecedor</Label><Input id="purchase-supplier" maxLength={160} value={form.supplier_name} onChange={e=>field("supplier_name",e.target.value)}/></div><div className="space-y-2"><Label htmlFor="purchase-date">Data *</Label><Input id="purchase-date" type="date" required value={form.purchase_date} onChange={e=>field("purchase_date",e.target.value)}/></div></div><div className="space-y-2"><Label htmlFor="purchase-notes">Observações</Label><textarea id="purchase-notes" maxLength={1000} rows={3} className="focus-ring w-full rounded-xl border bg-background px-3 py-2 text-sm" value={form.notes} onChange={e=>field("notes",e.target.value)}/></div>
 <section aria-labelledby="purchase-items"><div className="flex flex-wrap items-center justify-between gap-2"><h2 id="purchase-items" className="font-semibold">Itens</h2><Button variant="outline" size="sm" disabled={!products.length||form.items.length>=products.length} onClick={()=>{const product=products.find(p=>!form.items.some(item=>item.product_id===p.id));if(product)field("items",[...form.items,{product_id:product.id,quantity:"1",unit_cost:product.cost_price==null?"0":String(product.cost_price).replace(".",",")}])}}><Plus className="h-4 w-4"/>Adicionar produto</Button></div><div className="mt-3 space-y-3">{form.items.map((item,index)=>{const product=productMap.get(item.product_id);return <div key={index} className="grid gap-3 rounded-xl border p-3 md:grid-cols-[minmax(0,1fr)_8rem_9rem_9rem_auto] md:items-end"><div className="space-y-2"><Label htmlFor={`purchase-product-${index}`}>Produto *</Label><Select id={`purchase-product-${index}`} value={item.product_id} onChange={e=>{const next=productMap.get(e.target.value);itemField(index,"product_id",e.target.value);if(next?.cost_price!=null)itemField(index,"unit_cost",String(next.cost_price).replace(".",","))}}>{products.map(p=><option key={p.id} value={p.id} disabled={form.items.some((row,i)=>i!==index&&row.product_id===p.id)}>{p.name}{!p.active?" (inativo)":""}</option>)}</Select></div><div className="space-y-2"><Label htmlFor={`purchase-quantity-${index}`}>Quantidade *</Label><Input id={`purchase-quantity-${index}`} inputMode="decimal" required value={item.quantity} onChange={e=>itemField(index,"quantity",e.target.value)}/></div><div className="space-y-2"><Label htmlFor={`purchase-cost-${index}`}>Custo unitário *</Label><Input id={`purchase-cost-${index}`} inputMode="decimal" required value={item.unit_cost} onChange={e=>itemField(index,"unit_cost",e.target.value)}/></div><div><p className="text-xs text-muted">Subtotal</p><p className="mt-2 font-semibold tabular-nums">{formatCatalogBRL(purchaseSubtotal(item.quantity.replace(",","."),item.unit_cost.replace(",","."))||0)}</p></div><Button size="icon" variant="ghost" aria-label={`Remover ${product?.name??"produto"}`} disabled={form.items.length===1} onClick={()=>field("items",form.items.filter((_,i)=>i!==index))}><Trash2 className="h-4 w-4"/></Button></div>})}</div></section>
 <div className="flex flex-wrap items-center justify-between gap-3 border-t pt-5"><div><p className="text-xs text-muted">Total calculado</p><p className="text-xl font-semibold tabular-nums">{formatCatalogBRL(total)}</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/compras" className="focus-ring inline-flex h-11 items-center rounded-xl px-4 text-sm font-semibold text-muted hover:bg-surface">Cancelar</Link><Button type="submit" variant="outline" disabled={pending}>{pending?"Salvando…":"Salvar rascunho"}</Button><Button disabled={pending} onClick={()=>{if(window.confirm("Confirmar a compra e adicionar os itens ao estoque?"))submit(true)}}>{pending?"Confirmando…":"Confirmar compra"}</Button></div></div>{error&&<p role="alert" className="text-sm text-danger">{error}</p>}</form></Card></>;
}
