import "server-only";
import { requireBusinessModule } from "@/lib/auth/business-module";
import { createClient } from "@/lib/supabase/server";
import { parsePurchaseInput,purchaseError,type Purchase,type PurchaseItem } from "@/lib/purchases";
import { validCatalogId,type Product } from "@/lib/product-catalog";
import type { ActionResult } from "@/types/business";

const productFields="id,category_id,name,sku,barcode,unit,cost_price,sale_price,minimum_stock,active";
async function context(){const business=await requireBusinessModule("management");return {business,supabase:await createClient()};}
export async function listPurchases(){const {business,supabase}=await context();const {data,error}=await supabase.from("purchases").select("id,status,supplier_name,purchase_date,notes,total_amount,confirmed_at,created_at").eq("business_id",business.id).order("purchase_date",{ascending:false}).order("created_at",{ascending:false}).limit(100);if(error)throw new Error("Não foi possível carregar as compras.");const ids=(data??[]).map(row=>row.id);const itemResult=ids.length?await supabase.from("purchase_items").select("purchase_id").eq("business_id",business.id).in("purchase_id",ids):{data:[],error:null};if(itemResult.error)throw new Error("Não foi possível carregar as compras.");const counts=new Map<string,number>();for(const item of itemResult.data)counts.set(item.purchase_id,(counts.get(item.purchase_id)??0)+1);return (data??[]).map(row=>({...row,item_count:counts.get(row.id)??0})) as Purchase[];}
export async function getPurchaseEditor(id?:string){const {business,supabase}=await context();const productsResult=await supabase.from("products").select(productFields).eq("business_id",business.id).order("name");if(productsResult.error)throw new Error("Não foi possível carregar os produtos.");let purchase:Purchase|null=null,items:PurchaseItem[]=[];if(id){if(!validCatalogId(id))return {purchase:null,items,products:productsResult.data as Product[]};const result=await supabase.from("purchases").select("id,status,supplier_name,purchase_date,notes,total_amount,confirmed_at,created_at").eq("business_id",business.id).eq("id",id).maybeSingle();if(result.error)throw new Error("Não foi possível carregar a compra.");purchase=result.data as Purchase|null;if(purchase){const itemResult=await supabase.from("purchase_items").select("id,product_id,quantity,unit_cost,product:products(name,unit,active)").eq("business_id",business.id).eq("purchase_id",id).order("created_at");if(itemResult.error)throw new Error("Não foi possível carregar os itens.");items=itemResult.data as unknown as PurchaseItem[];}}return {purchase,items,products:productsResult.data as Product[]};}
export async function savePurchase(id:string|null,input:unknown):Promise<ActionResult<{id:string}>>{const {supabase}=await context();if(id!==null&&!validCatalogId(id))return {ok:false,message:"Compra inválida."};let value;try{value=parsePurchaseInput(input)}catch(error){return {ok:false,message:(error as Error).message}}const {data,error}=await supabase.rpc("save_admin_purchase_draft",{p_purchase_id:id,p_supplier_name:value.supplier_name||null,p_purchase_date:value.purchase_date,p_notes:value.notes||null,p_items:value.items});if(error)return {ok:false,message:purchaseError(error)};return {ok:true,message:"Rascunho salvo.",data:{id:data}};}
export async function confirmPurchase(id:string|null,input:unknown):Promise<ActionResult<{id:string}>>{const saved=await savePurchase(id,input);if(!saved.ok||!saved.data)return saved;const purchaseId=saved.data.id;const {supabase}=await context();const {error}=await supabase.rpc("confirm_admin_purchase",{p_purchase_id:purchaseId});if(error)return {ok:false,message:purchaseError(error)};return {ok:true,message:"Compra confirmada e estoque atualizado.",data:{id:purchaseId}};}
