"use client";

import { Check, ChevronLeft, ChevronRight, Plus, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useMockApp } from "@/components/mock-app-provider";
import { Button } from "@/components/ui/button";
import { Input, Label } from "@/components/ui/field";
import { Switch } from "@/components/ui/switch";
import { Logo } from "@/components/ui/logo";
import { classes } from "@/lib/classes";
import { palettes, publicDomain } from "@/mocks/app";
import type { GroupConfig } from "@/types/scheduling";

const steps = ["Negócio", "Agenda", "Horários", "Aparência", "Pronto"];

export function OnboardingWizard() {
  const router = useRouter(), { state, update } = useMockApp();
  const [step, setStep] = useState(0);
  const setGroup = (key: "group1" | "group2", patch: Partial<GroupConfig>) => update({ [key]: { ...state[key], ...patch } });
  return <main className="min-h-screen bg-surface px-4 py-8"><div className="mx-auto w-full max-w-xl">
    <header className="mb-6"><p className="text-sm font-medium text-primary">Passo {step + 1} de {steps.length}</p><h1 className="mt-1 text-2xl font-semibold">{steps[step]}</h1><div className="mt-4 flex gap-1.5">{steps.map((label, index) => <span key={label} className={classes("h-1.5 flex-1 rounded-full", index <= step ? "bg-primary" : "bg-border")} />)}</div></header>
    <div className="rounded-2xl border bg-background p-5 sm:p-6">
      {step === 0 ? <div className="space-y-5"><div className="flex items-center gap-3"><Logo name={state.business.name} size="lg" /><div><p className="text-sm font-medium">Logo do negócio</p><p className="text-xs text-muted">Upload será conectado ao backend depois.</p></div></div><div className="space-y-2"><Label htmlFor="business-name">Nome do negócio</Label><Input id="business-name" value={state.business.name} onChange={(event) => update({ business: { ...state.business, name: event.target.value } })} /></div><div className="space-y-2"><Label htmlFor="business-whatsapp">WhatsApp</Label><Input id="business-whatsapp" value={state.business.whatsapp} onChange={(event) => update({ business: { ...state.business, whatsapp: event.target.value } })} /></div><div className="space-y-2"><Label htmlFor="business-slug">URL personalizada</Label><div className="flex items-center rounded-xl border bg-card px-3"><span className="text-sm text-muted">{publicDomain}/</span><input id="business-slug" className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none" value={state.business.slug} onChange={(event) => update({ business: { ...state.business, slug: event.target.value.toLowerCase().replace(/\s+/g, "-") } })} /></div></div></div> : null}
      {step === 1 ? <div className="space-y-5">{(["group1", "group2"] as const).map((key, index) => { const group = state[key]; return <section key={key} className="rounded-xl border p-4"><div className="grid grid-cols-[1fr_auto] items-center gap-3"><div className="space-y-1"><Label htmlFor={`${key}-label`}>Nome do Grupo {index + 1}</Label><Input id={`${key}-label`} value={group.label} onChange={(event) => setGroup(key, { label: event.target.value })} /></div><Switch checked={group.enabled} onChange={(enabled) => setGroup(key, { enabled })} label={`Ativar Grupo ${index + 1}`} /></div><div className={classes("mt-3 space-y-2", !group.enabled && "opacity-45")}>{group.options.map((option) => <div key={option.id} className="flex gap-2"><Input value={option.name} onChange={(event) => setGroup(key, { options: group.options.map((item) => item.id === option.id ? { ...item, name: event.target.value } : item) })} /><Button variant="ghost" size="icon" aria-label="Remover opção" onClick={() => setGroup(key, { options: group.options.filter((item) => item.id !== option.id) })}><Trash2 className="h-4 w-4" /></Button></div>)}<Button variant="outline" size="sm" onClick={() => setGroup(key, { options: [...group.options, { id: `${key}-${Date.now()}`, name: "Nova opção", durationMinutes: 30 }] })}><Plus className="h-4 w-4" />Adicionar opção</Button></div></section>; })}<div className="rounded-xl border p-4"><p className="text-sm font-semibold">Modo de duração</p><div className="mt-3 grid gap-2">{[{ id: "fixed" as const, label: "Duração fixa" }, { id: "fixed-multiple" as const, label: "Duração fixa + múltiplos blocos" }, { id: "group2" as const, label: `Duração pelo ${state.group2.label}` }].map((mode) => <button key={mode.id} type="button" onClick={() => update({ duration: { ...state.duration, mode: mode.id } })} className={classes("focus-ring rounded-xl border p-3 text-left text-sm font-medium", state.duration.mode === mode.id && "border-primary bg-primary/5 text-primary")}>{mode.label}</button>)}</div></div></div> : null}
      {step === 2 ? <div className="space-y-2">{state.hours.map((hour) => <div key={hour.day} className="grid gap-3 rounded-xl border p-3 sm:grid-cols-[1fr_auto] sm:items-center"><div className="flex items-center gap-3"><Switch checked={hour.enabled} onChange={(enabled) => update({ hours: state.hours.map((item) => item.day === hour.day ? { ...item, enabled } : item) })} label={`Ativar ${hour.label}`} /><span className="text-sm font-medium">{hour.label}</span></div><div className="flex gap-2"><Input type="time" className="min-w-0" disabled={!hour.enabled} value={hour.start} onChange={(event) => update({ hours: state.hours.map((item) => item.day === hour.day ? { ...item, start: event.target.value } : item) })} /><Input type="time" className="min-w-0" disabled={!hour.enabled} value={hour.end} onChange={(event) => update({ hours: state.hours.map((item) => item.day === hour.day ? { ...item, end: event.target.value } : item) })} /></div></div>)}</div> : null}
      {step === 3 ? <div className="grid grid-cols-2 gap-3">{palettes.map((palette) => <button key={palette.id} type="button" onClick={() => update({ paletteId: palette.id })} className={classes("focus-ring rounded-xl border p-3 text-left", state.paletteId === palette.id && "border-primary bg-primary/5")}><div className="flex gap-1.5">{[palette.primary, palette.accent, palette.surface, palette.text].map((color) => <span key={color} className="h-6 w-6 rounded-full border" style={{ background: color }} />)}</div><p className="mt-2 text-sm font-medium">{palette.name}</p></button>)}</div> : null}
      {step === 4 ? <div className="py-6 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-primary text-white"><Check className="h-7 w-7" /></span><h2 className="mt-4 text-xl font-semibold">Tudo pronto!</h2><p className="mt-1 text-sm text-muted">Sua página está disponível em <strong className="text-foreground">{publicDomain}/{state.business.slug}</strong></p><Button className="mt-6 w-full" onClick={() => router.push("/admin")}>Ir para o painel</Button></div> : null}
    </div>
    {step < 4 ? <div className="mt-5 flex justify-between gap-3"><Button variant="ghost" onClick={() => step === 0 ? router.push("/") : setStep(step - 1)}><ChevronLeft className="h-4 w-4" />Voltar</Button><Button onClick={() => setStep(step + 1)}>Continuar<ChevronRight className="h-4 w-4" /></Button></div> : null}
  </div></main>;
}
